version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    command: air .air.toml -b 0.0.0.0