// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Login with username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login to your account",
                "parameters": [
                    {
                        "description": "UserLogin",
                        "name": "userModelArgs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserLoginArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserLoginResult"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Register and create account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Create a account",
                "parameters": [
                    {
                        "description": "UserRegister",
                        "name": "userModelArgs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRegisterArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserRegisterResult"
                        }
                    }
                }
            }
        },
        "/token-check": {
            "post": {
                "description": "Token check method for authentication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Check validity of token",
                "parameters": [
                    {
                        "description": "TokenCheck",
                        "name": "tokenCheckArgs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenCheckArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TokenCheckResult"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Result": {
            "type": "object",
            "properties": {
                "error_code": {
                    "$ref": "#/definitions/utils.Error"
                },
                "error_description": {
                    "type": "string"
                },
                "error_exception": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.TokenCheckArgs": {
            "type": "object",
            "properties": {
                "client_time": {
                    "type": "string"
                }
            }
        },
        "models.TokenCheckResult": {
            "type": "object",
            "properties": {
                "client_time": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/models.Result"
                },
                "server_time": {
                    "type": "string"
                }
            }
        },
        "models.UserLoginArgs": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.UserLoginResult": {
            "type": "object",
            "properties": {
                "authentication_token": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/models.Result"
                },
                "user_infos": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "models.UserRegisterArgs": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "validate_password": {
                    "type": "string"
                }
            }
        },
        "models.UserRegisterResult": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/models.Result"
                }
            }
        },
        "utils.Error": {
            "type": "string",
            "enum": [
                "ERR0303",
                "ERR0304",
                "ERR0401",
                "ERR0402",
                "ERR0403",
                "ERR0404",
                "ERR0405",
                "ERR0406",
                "ERR0407"
            ],
            "x-enum-varnames": [
                "ERR0303",
                "ERR0304",
                "ERR0401",
                "ERR0402",
                "ERR0403",
                "ERR0404",
                "ERR0405",
                "ERR0406",
                "ERR0407"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
