basePath: /
definitions:
  models.Result:
    properties:
      error_code:
        $ref: '#/definitions/utils.Error'
      error_description:
        type: string
      error_exception:
        type: string
      success:
        type: boolean
    type: object
  models.UserLoginArgs:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.UserLoginResult:
    properties:
      authentication_token:
        type: string
      result:
        $ref: '#/definitions/models.Result'
    type: object
  utils.Error:
    enum:
    - ERR0303
    - ERR0304
    - ERR0401
    - ERR0405
    type: string
    x-enum-varnames:
    - ERR0303
    - ERR0304
    - ERR0401
    - ERR0405
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login with username and password
      parameters:
      - description: UserLogin
        in: body
        name: userModelArgs
        required: true
        schema:
          $ref: '#/definitions/models.UserLoginArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserLoginResult'
      summary: Login to your account
      tags:
      - Login
swagger: "2.0"
